# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide6 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(400, 342)
        widget.setMinimumSize(QtCore.QSize(0, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("image/ico.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        widget.setWindowIcon(icon)
        widget.setStyleSheet("QWidget{\n"
                             "    background-color: rgb(213, 213, 213);\n"
                             "    font: 75 15pt;\n"
                             "    top-radius:10px;\n"
                             "}\n"
                             "QPushButton{\n"
                             "    background-color: qlineargradient(spread:reflect, x1:0.011, y1:0.512455, x2:0.017, y2:0, stop:0 rgba(0, 0, 0, 255), stop:0.829545 rgba(241, 231, 231, 255));\n"
                             "    color: rgb(0, 255, 0);\n"
                             "    border-radius:10px\n"
                             "}\n"
                             "\n"
                             "QPushButton:hover{\n"
                             "    background-color: qlineargradient(spread:reflect, x1:0.011, y1:0.512455, x2:0.017, y2:0, stop:0.284091 rgba(135, 122, 122, 255), stop:0.829545 rgba(241, 231, 231, 255));\n"
                             "}\n"
                             "\n"
                             "QPushButton:disabled{\n"
                             "    color: rgb(0, 0, 0);\n"
                             "    background-color: rgb(200, 200, 200);\n"
                             "}\n"
                             "\n"
                             "QPushButton:pressed{\n"
                             "    color: rgb(255, 255, 255);\n"
                             "    background-color: rgb(0, 0, 0);\n"
                             "}\n"
                             "\n"
                             "#pushButton_4,#pushButton_2{\n"
                             "    background-color: qlineargradient(spread:reflect, x1:0.5, y1:1, x2:1, y2:0.983, stop:0.102273 rgba(23, 9, 9, 255), stop:1 rgba(255, 255, 255, 255));\n"
                             "    color: rgb(0, 255, 0);\n"
                             "}\n"
                             "\n"
                             "#pushButton_4:hover,#pushButton_2:hover{\n"
                             "    background-color: qlineargradient(spread:reflect, x1:0.5, y1:1, x2:1, y2:0.983, stop:0.102273 rgba(73, 73, 73, 254), stop:1 rgba(255, 255, 255, 255));\n"
                             "}\n"
                             "#pushButton_4:pressed,#pushButton_2:pressed{\n"
                             "    color: rgb(255, 255, 255);\n"
                             "    background-color: rgb(0, 0, 0);\n"
                             "}\n"
                             "#pushButton_4:disabled,#pushButton_2:disabled{\n"
                             "    color: rgb(0, 0, 0);\n"
                             "    background-color: rgb(200, 200, 200);\n"
                             "}\n"
                             "\n"
                             "\n"
                             "QComboBox {\n"
                             "    background-color: rgb(247, 247, 247);\n"
                             "}\n"
                             "\n"
                             "QLineEdit {    \n"
                             "    border-radius:10px;\n"
                             "    border-width:1px;\n"
                             "    border-color: rgb(170, 85, 0);\n"
                             "    border-style:solid;\n"
                             "}\n"
                             "\n"
                             "QLineEdit:hover {\n"
                             "    background-color: rgb(239, 239, 239);\n"
                             "    border-color: rgb(170, 170, 255);\n"
                             "}\n"
                             "QLineEdit:focus ,QComboBox:foucs {\n"
                             "    background-color: rgb(239, 239, 239);\n"
                             "    border-bottom-color: rgb(85, 170, 0);\n"
                             "}\n"
                             "QComboBox{\n"
                             "    border-radius:10px;\n"
                             "}\n"
                             "\n"
                             "QComboBox:hover{\n"
                             "    background-color: rgb(240, 240, 240);\n"
                             "}\n"
                             "\n"
                             "QComboBox::down-arrow {\n"
                             "    width:30px;\n"
                             "    border: 1px solid green;\n"
                             "}\n"
                             "\n"
                             "\n"
                             ""
                             )
        self.gridLayout = QtWidgets.QGridLayout(widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(widget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_2.setContentsMargins(-1, 15, -1, -1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setStyleSheet("font: 15pt ;")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 3, 2, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_3.setStyleSheet("font: 12pt;")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.page)
        self.label_2.setMinimumSize(QtCore.QSize(0, 30))
        self.label_2.setStyleSheet("font: 75 12pt;\n"
                                   "color: rgb(85, 0, 255);"
                                   )
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.comboBox = QtWidgets.QComboBox(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox.setStyleSheet("font: 12pt;\n"
                                    "color: rgb(255, 0, 0);"
                                    )
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.gridLayout_2.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.page)
        self.label.setStyleSheet("font: 75 20pt;\n"
                                 "color: rgb(255, 0, 0);"
                                 )
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 3, 0, 1, 2)
        self.lineEdit = QtWidgets.QLineEdit(self.page)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit.setStyleSheet("font: 12pt;")
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_2.addWidget(self.lineEdit, 2, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setStyleSheet("font: 12pt;")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_2.addWidget(self.pushButton, 2, 2, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 3)
        self.gridLayout_2.setColumnStretch(1, 5)
        self.gridLayout_2.setColumnStretch(2, 2)
        self.lineEdit.raise_()
        self.pushButton_2.raise_()
        self.pushButton_3.raise_()
        self.label_2.raise_()
        self.comboBox.raise_()
        self.label.raise_()
        self.pushButton.raise_()
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_3.setContentsMargins(-1, 15, -1, -1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_3 = QtWidgets.QLabel(self.page_2)
        self.label_3.setStyleSheet("font: 75 20pt;\n"
                                   "color: rgb(255, 0, 0);"
                                   )
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setWordWrap(True)
        self.label_3.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 3, 0, 1, 2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.page_2)
        self.lineEdit_2.setMinimumSize(QtCore.QSize(0, 30))
        self.lineEdit_2.setStyleSheet("font: 12pt;")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 2, 0, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.page_2)
        self.label_4.setMinimumSize(QtCore.QSize(0, 30))
        self.label_4.setStyleSheet("font: 75 12pt;\n"
                                   "color: rgb(85, 0, 255);"
                                   )
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setStyleSheet("font: 12pt;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 1, 2, 2, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setStyleSheet("font: 15pt ;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_3.addWidget(self.pushButton_4, 3, 2, 1, 1)
        self.comboBox_2 = QtWidgets.QComboBox(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_2.setStyleSheet("font: 12pt;\n"
                                      "color: rgb(255, 0, 0);"
                                      )
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_2, 0, 1, 1, 1)
        self.comboBox_3 = QtWidgets.QComboBox(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox_3.setStyleSheet("font: 12pt;\n"
                                      "color: rgb(255, 0, 0);"
                                      )
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.gridLayout_3.addWidget(self.comboBox_3, 1, 1, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(0, 30))
        self.pushButton_6.setStyleSheet("font: 12pt;")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_3.addWidget(self.pushButton_6, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.page_2)
        self.label_5.setMinimumSize(QtCore.QSize(0, 30))
        self.label_5.setStyleSheet("font: 75 12pt;\n"
                                   "color: rgb(85, 0, 255);"
                                   )
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 1, 0, 1, 1)
        self.gridLayout_3.setColumnStretch(0, 3)
        self.gridLayout_3.setColumnStretch(1, 5)
        self.gridLayout_3.setColumnStretch(2, 2)
        self.gridLayout_3.setRowStretch(0, 1)
        self.gridLayout_3.setRowStretch(1, 1)
        self.gridLayout_3.setRowStretch(2, 1)
        self.gridLayout_3.setRowStretch(3, 7)
        self.stackedWidget.addWidget(self.page_2)
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.label_2.setBuddy(self.comboBox)
        self.label.setBuddy(self.pushButton_2)
        self.label_3.setBuddy(self.pushButton_4)
        self.label_4.setBuddy(self.comboBox_2)
        self.label_5.setBuddy(self.comboBox_3)

        self.retranslateUi(widget)
        self.stackedWidget.setCurrentIndex(1)
        self.pushButton_6.clicked.connect(widget.refresh)
        self.comboBox_2.currentTextChanged['QString'].connect(widget.type1)
        self.comboBox_3.currentTextChanged['QString'].connect(widget.type2)
        self.pushButton_3.clicked.connect(widget.return_func)
        self.pushButton_5.clicked.connect(widget.run)
        self.pushButton_4.clicked.connect(widget.pic)
        self.pushButton.clicked.connect(widget.run)
        self.pushButton_2.clicked.connect(widget.pic)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "条形码生成"))
        self.pushButton_2.setText(_translate("widget", "复\n"
                                                       "制\n"
                                                       "图\n"
                                                       "片\n"
                                                       "到\n"
                                                       "粘\n"
                                                       "贴\n"
                                                       "板"
                                             )
                                  )
        self.pushButton_3.setText(_translate("widget", "返回"))
        self.label_2.setText(_translate("widget", "选择类型3："))
        self.comboBox.setItemText(0, _translate("widget", "正在获取"))
        self.label.setText(_translate("widget", "此类型需要\n"
                                                "跳转到本页面\n"
                                                "点击开始\n"
                                                "开始生成\n"
                                                "点击返回\n"
                                                "回到初始界面"
                                      )
                           )
        self.pushButton.setText(_translate("widget", "开始生成"))
        self.label_3.setText(_translate("widget", "正在获取所有类型"))
        self.label_4.setText(_translate("widget", "选择类型1："))
        self.pushButton_5.setText(_translate("widget", "开始生成"))
        self.pushButton_4.setText(_translate("widget", "复\n"
                                                       "制\n"
                                                       "到\n"
                                                       "粘\n"
                                                       "贴\n"
                                                       "板"
                                             )
                                  )
        self.comboBox_2.setItemText(0, _translate("widget", "正在获取"))
        self.comboBox_3.setItemText(0, _translate("widget", "正在获取"))
        self.pushButton_6.setText(_translate("widget", "刷新"))
        self.label_5.setText(_translate("widget", "选择类型2："))

class Widget(QtWidgets.QWidget):
    def refresh(self):
        pass

    def type1(self):
        pass

    def type2(self):
        pass

    def return_func(self):
        pass

    def run(self):
        pass

    def pic(self):
        pass


# import images_rc_rc

if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    widget = Widget()
    ui = Ui_widget()
    ui.setupUi(widget)
    widget.show()
    sys.exit(app.exec())
